### ISSUE TITLE
Docker local user "mid" not allowed to use apt-get.

### ISSUE THREAD

**Issue by JustinHenryLo** [bmoers/docker-mid-server#18]
Im trying to install nodejs but mid account seems like it doesn't have enough privilege. Are there other accounts/passwords I can use to install packages? Or is there a better way of installing additional requirements?

**Comment by bmoers** [comment]
Due to security reasons the process does not run as Root.
But, if you exec into the container with root (-u=0) you'll be able to install additional components:
```bash
$ docker exec -it -u=0 065718ab2ce6 /bin/bash
root@065718ab2ce6:/# 
```
However, I do not recommend to change the container content after boot in production (as it's not persistent on re-creation fo the container).
Could you share your use case for NodeJs?

Cheers
Boris

**Comment by JustinHenryLo** [comment]
I was tasked to make a custom report generator. They want to feed in a report template and I was tasked to populate the data. I used Node to fill it in.  
Im not sure if this is the right way to integrate it, is this method an unconventional way to use MID servers?

**Comment by bmoers** [comment]
MID is the perfect choice to load data into ServiceNow. But in your case, it’s better to run the report generator in a separate Docker container and configure a Datasource in ServiceNow to connect to it via the MID server. (It’s bad practice to run multiple processes in Docker)

**Comment by JustinHenryLo** [comment]
Thanks for the suggestion. I will look into it as I am quite inexperienced in the best practices of Docker and MID Servers.
